### ISSUE TITLE
Someday's dinner at 2018-01-08

### ISSUE THREAD

**Issue by ghost** [hacusk-room/dinner#20]
# 飯
- ***山岡家 上磯店*****もやし特製味噌**

**Comment by hacusk** [comment]
# bugラベルで草

**Comment by ghost** [comment]
ラベル活用していこうな
色は適当なんで気に入らなかったら変えていいよ

**Comment by hacusk** [comment]
やったぜ。

8日の夜20時-21時ごろに帰宅する予定なので僕も行きたい

**Comment by ghost** [comment]
数日前にTwitterで言ったとおりになる予定なのでよろ

**Comment by hacusk** [comment]
なるなる

**Comment by hacusk** [comment]
# ***山岡家***

キメました。
